version: '3'

services:
  zk-proof-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./target:/zk/target
    restart: unless-stopped
    environment:
      - NODE_ENV=production 